FLASH_WRITER_URL = "git://github.com/SolidRun/rzg2_flash_writer"
BRANCH = "solidrun"
SRCREV = "31cdf49867acc686a6f4c4755d2a9728beb07c95"

do_compile:rzg2lc-sr-som() {
	cd ${S}

	oe_runmake DEVICE=RZG2LC DDR_TYPE=DDR4 DDR_SIZE=512MB_1PCS SWIZZLE=T3BC FILENAME_ADD=_RZG2LC_HUMMINGBOARD
	oe_runmake DEVICE=RZG2LC DDR_TYPE=DDR4 DDR_SIZE=1GB_1PCS SWIZZLE=T3BC FILENAME_ADD=_RZG2LC_HUMMINGBOARD
	oe_runmake DEVICE=RZG2LC DDR_TYPE=DDR4 DDR_SIZE=2GB_1PCS SWIZZLE=T3BC FILENAME_ADD=_RZG2LC_HUMMINGBOARD
}
