# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
# Explicitly list to avoid wildcard matching sublayer dynamic-layers
BBFILES += "${LAYERDIR}/recipes-kernel/*/*.bb \
            ${LAYERDIR}/recipes-kernel/*/*.bbappend \
            ${LAYERDIR}/recipes-solidrun/*/*.bb \
            ${LAYERDIR}/recipes-solidrun/*/*.bbappend"

BBFILE_COLLECTIONS += "solidrun-rz"
BBFILE_PATTERN_solidrun-rz = "^${LAYERDIR}/"
BBFILE_PRIORITY_solidrun-rz = "15"
LAYERVERSION_solidrun-rz = "1"
LAYERSERIES_COMPAT_solidrun-rz = "scarthgap"

# enable virtualization features if meta-virtualization is available
# this reduces user instructions enabling docker to "bitbake-layers add-layer .." only.
DISTRO_FEATURES:append = " ${@bb.utils.contains('BBFILE_COLLECTIONS', 'virtualization-layer', 'virtualization docker', '', d)} "
